version: "3.7"

services:
  traefik:
    image: "traefik:v3.7.11"
    container_name: "traefik"
    restart: unless-stopped
    hostname: "traefik"
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
      - "./users_credentials:/users_credentials:ro"
    labels:
      - "traefik.enable=true"
      # Secure Dashboard Routing
      - "traefik.http.routers.dashboard.rule=Host(`traefik.$MY_DOMAIN`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=lets-encr"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/users_credentials"
      # Wildcard Certificate
      - "traefik.http.routers.traefik.tls.certresolver=lets-encr"
      - "traefik.http.routers.traefik.tls.domains[0].main=*.$MY_DOMAIN"
      - "traefik.http.routers.traefik.tls.domains[0].sans=$MY_DOMAIN"

networks:
  default:
    external:
      name: $DEFAULT_NETWORK
