## STATIC CONFIGURATION WITH TCP & UDP ENTRYPOINTS
core:
  defaultRuleSyntax: v2

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  # Custom TCP entrypoints:
  postgres:
    address: ":5432"
  redis:
    address: ":6379"
  # Custom UDP entrypoint:
  minecraft_udp:
    address: ":25565/udp"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_net

certificatesResolvers:
  lets-encr:
    acme:
      email: your-email@example.com
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
