services:
  api-service:
    image: "traefik/whoami"
    container_name: "api-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-service.entrypoints=websecure"
      - "traefik.http.routers.api-service.rule=Host(`api.$MY_DOMAIN`)"
      - "traefik.http.routers.api-service.tls.certresolver=lets-encr"
      - "traefik.http.routers.api-service.middlewares=api-ratelimit,sec-headers"
      # Inline Rate Limit Middleware
      - "traefik.http.middlewares.api-ratelimit.ratelimit.average=20"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=10"
      # Inline Security Headers
      - "traefik.http.middlewares.sec-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.sec-headers.headers.browserXssFilter=true"

networks:
  default:
    name: 
    external: true
