services:
  apache:
    image: "httpd:latest"
    container_name: "apache"
    hostname: "apache"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.entrypoints=web"
      - "traefik.http.routers.apache.rule=Host(`apache.$MY_DOMAIN`)"

networks:
  default:
    name: ${DEFAULT_NETWORK:-traefik-public}
    external: true
