services:
  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    hostname: "portainer"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "portainer_data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.$MY_DOMAIN`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  default:
    name: 
    external: true

volumes:
  portainer_data:
