## STATIC CONFIGURATION WITH CROWDSEC BOUNCER PLUGIN
log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

experimental:
  plugins:
    crowdsec:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.3.3"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_net
  file:
    directory: "/dynamic_conf"
    watch: true
